# Generated by Django 5.0.4 on 2024-05-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='certificate',
            field=models.FileField(null=True, upload_to='media/certificates'),
        ),
    ]
